// Generated by Zero1 compiler
// Target: TypeScript

// IR:
// ; IR for module: http::server
// ; Version: 1.0
// ; Context budget: Some(128)
// ; Capabilities: ["net"]
// 
// symbol_map
// import "std/http"
// type Health = Record([RecordField { name: "ok", ty: Path(["Bool"]), span: Span { start: 192, end: 200 } }, RecordField { name: "msg", ty: Path(["Str"]), span: Span { start: 202, end: 210 } }])
// fn handler(1 params) -> Path(["H.Res"]) eff ["pure"]
// fn serve(1 params) -> Path(["Unit"]) eff ["net"]

export {};
