[package]
name = "z1-lex"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
anyhow.workspace = true
serde.workspace = true
thiserror.workspace = true
z1-ast = { path = "../z1-ast" }
logos.workspace = true
