// Generated by Zero1 compiler
// Target: TypeScript

// IR:
// ; IR for module: hello::world
// ; Version: 0.1.0
// ; Context budget: Some(64)
// ; Capabilities: []
// 
// symbol_map
// type name = Path(["Str"])
// fn greet(1 params) -> Path(["Str"]) eff ["pure"]

export {};
