[package]
name = "z1-codegen-wasm"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
z1-ir = { path = "../z1-ir" }
anyhow.workspace = true
serde.workspace = true
thiserror.workspace = true
