[package]
name = "z1-hash"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish = false

 [dependencies]
sha3.workspace = true
z1-ast = { path = "../z1-ast" }

[dev-dependencies]
z1-parse = { path = "../z1-parse" }
